sonar.projectKey=notes-app
sonar.projectName=Notes App
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/src

sonar.test.inclusions=backend/test/**/*.test.js,frontend/src/**/*.test.jsx,frontend/src/**/*.test.js

sonar.exclusions=\
  **/node_modules/**,\
  **/coverage/**,\
  **/dist/**,\
  **/build/**,\
  **/*.config.js,\
  **/*.config.cjs,\
  backend/test/**,\
  frontend/src/**/*.test.jsx,\
  frontend/src/**/*.test.js

sonar.coverage.exclusions=\
  **/node_modules/**,\
  backend/test/**,\
  frontend/src/**/*.test.jsx,\
  frontend/src/**/*.test.js,\
  **/*.config.js,\
  **/*.config.cjs,\
  backend/server.js,\
  frontend/src/main.jsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
